window.RESONANCE_ATLAS_3D_DATA = {
  stateKey: "tuner.resonanceAtlas3d.v1_2",
  version: "1.2",
  layoutMode: "flower",
  journeyTypes: {
    destination: "I want to go there.",
    transition: "I want to move out of my current state.",
    exploration: "I do not need a fixed destination."
  },
  rooms: [
    {
      id: "you",
      name: "YOU",
      type: "origin",
      phrase: "Start where you are.",
      meaning: "Start where you are.",
      color: "#9ad4c8",
      position: [0, 0, 0],
      radius: 112,
      state: { activation: 0, attention: 0, regulation: 0 },
      journeyIds: ["find_frequency"]
    },
    {
      id: "energize",
      name: "ENERGIZE",
      type: "room",
      phrase: "Bring the system online.",
      meaning: "I want more energy.",
      color: "#d7bd72",
      position: [0, -276, 48],
      radius: 82,
      state: { activation: 1, attention: 0.2, regulation: -0.1 },
      journeyIds: ["wake_up", "charge"]
    },
    {
      id: "focus",
      name: "FOCUS",
      type: "room",
      phrase: "Gather your attention.",
      meaning: "I want to gather my attention.",
      color: "#8ea7ff",
      position: [-238, -118, 34],
      radius: 84,
      state: { activation: 0.4, attention: 1, regulation: 0.4 },
      journeyIds: ["clear_mind", "get_energy"]
    },
    {
      id: "explore",
      name: "EXPLORE",
      type: "room",
      phrase: "Open the field.",
      meaning: "I want to open up.",
      color: "#d99ad8",
      position: [238, -118, -28],
      radius: 88,
      state: { activation: 0.2, attention: -1, regulation: -0.1 },
      journeyIds: ["explore", "free_crossing"]
    },
    {
      id: "ground",
      name: "GROUND",
      type: "room",
      phrase: "Come back into the body.",
      meaning: "I want to feel more present in my body.",
      color: "#c7aa6c",
      position: [-238, 122, -34],
      radius: 92,
      state: { activation: -0.2, attention: 0.2, regulation: 0.9 },
      journeyIds: ["ground", "recover"]
    },
    {
      id: "release",
      name: "RELEASE",
      type: "room",
      phrase: "Let tension soften.",
      meaning: "I want to let go.",
      color: "#f09a86",
      position: [238, 122, 40],
      radius: 84,
      state: { activation: -0.3, attention: -0.4, regulation: -0.8 },
      journeyIds: ["cycle_ease", "soft_wave"]
    },
    {
      id: "balance",
      name: "BALANCE",
      type: "room",
      phrase: "Return toward center.",
      meaning: "I want to return toward equilibrium.",
      color: "#a8d8b5",
      position: [-118, 236, 22],
      radius: 80,
      state: { activation: 0, attention: 0, regulation: 1 },
      journeyIds: ["reset", "recenter"]
    },
    {
      id: "calm",
      name: "CALM",
      type: "room",
      phrase: "Let the system settle.",
      meaning: "I want to slow down.",
      color: "#7fcad0",
      position: [118, 236, 32],
      radius: 86,
      state: { activation: -0.7, attention: -0.1, regulation: 0.7 },
      journeyIds: ["vagal_reset", "breath_sync"]
    },
    {
      id: "drift",
      name: "DRIFT",
      type: "room",
      phrase: "Let wakefulness fade.",
      meaning: "I want to let wakefulness soften.",
      color: "#a69bdc",
      position: [0, 354, -48],
      radius: 86,
      state: { activation: -1, attention: -0.7, regulation: -0.2 },
      journeyIds: ["sleep_ready", "repair"]
    }
  ],
  journeys: {
    find_frequency: {
      id: "find_frequency",
      label: "Find Frequency",
      room: "you",
      type: "exploration",
      kind: "youTuner",
      description: "Start from the frequency that feels right now.",
      duration: null,
      composerData: null
    },
    vagal_reset: {
      id: "vagal_reset",
      label: "Vagal Reset",
      room: "calm",
      type: "transition",
      kind: "journey",
      journeyId: "vagal_reset",
      description: "Let the system settle.",
      duration: 300,
      composerData: { libraryId: "vagal_reset" }
    },
    breath_sync: {
      id: "breath_sync",
      label: "Breath Sync",
      room: "calm",
      type: "destination",
      kind: "journey",
      journeyId: "breath_sync",
      description: "A breathing-led settling journey.",
      duration: 300,
      composerData: { libraryId: "breath_sync" }
    },
    ground: {
      id: "ground",
      label: "Ground",
      room: "ground",
      type: "destination",
      kind: "journey",
      journeyId: "ground",
      description: "Come back into the body.",
      duration: 300,
      composerData: { libraryId: "ground" }
    },
    recover: {
      id: "recover",
      label: "Recover",
      room: "ground",
      type: "transition",
      kind: "journey",
      journeyId: "recover",
      description: "Move toward a steadier body state.",
      duration: 300,
      composerData: { libraryId: "recover" }
    },
    clear_mind: {
      id: "clear_mind",
      label: "Clear Mind",
      room: "focus",
      type: "destination",
      kind: "journey",
      journeyId: "clear_mind",
      description: "Gather attention without tightening.",
      duration: 300,
      composerData: { libraryId: "clear_mind" }
    },
    get_energy: {
      id: "get_energy",
      label: "Get Energy",
      room: "focus",
      type: "destination",
      kind: "journey",
      journeyId: "get_energy",
      description: "Bring alertness into focus.",
      duration: 300,
      composerData: { libraryId: "get_energy" }
    },
    explore: {
      id: "explore",
      label: "Explore",
      room: "explore",
      type: "exploration",
      kind: "journey",
      journeyId: "explore",
      description: "Open the field.",
      duration: 300,
      composerData: { libraryId: "explore" }
    },
    free_crossing: {
      id: "free_crossing",
      label: "Free Crossing",
      room: "explore",
      type: "exploration",
      kind: "journey",
      journeyId: "free_crossing",
      description: "Move without a fixed destination.",
      duration: 300,
      composerData: { libraryId: "free_crossing" }
    },
    cycle_ease: {
      id: "cycle_ease",
      label: "Cycle Ease",
      room: "release",
      type: "transition",
      kind: "journey",
      journeyId: "cycle_ease",
      description: "Loosen what is held.",
      duration: 300,
      composerData: { libraryId: "cycle_ease" }
    },
    soft_wave: {
      id: "soft_wave",
      label: "Soft Wave",
      room: "release",
      type: "destination",
      kind: "journey",
      journeyId: "soft_wave",
      description: "Let tension soften.",
      duration: 300,
      composerData: { libraryId: "soft_wave" }
    },
    sleep_ready: {
      id: "sleep_ready",
      label: "Sleep Ready",
      room: "drift",
      type: "destination",
      kind: "journey",
      journeyId: "sleep_ready",
      description: "Let wakefulness fade.",
      duration: 300,
      composerData: { libraryId: "sleep_ready" }
    },
    repair: {
      id: "repair",
      label: "Repair",
      room: "drift",
      type: "destination",
      kind: "journey",
      journeyId: "repair",
      description: "A softer passage toward rest.",
      duration: 300,
      composerData: { libraryId: "repair" }
    },
    wake_up: {
      id: "wake_up",
      label: "Wake Up",
      room: "energize",
      type: "destination",
      kind: "journey",
      journeyId: "get_energy",
      description: "Bring the system online.",
      duration: 300,
      composerData: { libraryId: "get_energy" }
    },
    charge: {
      id: "charge",
      label: "Charge",
      room: "energize",
      type: "destination",
      kind: "journey",
      journeyId: "classic",
      description: "Build a clear, active state.",
      duration: 300,
      composerData: { libraryId: "classic" }
    },
    reset: {
      id: "reset",
      label: "Reset",
      room: "balance",
      type: "transition",
      kind: "journey",
      journeyId: "recover",
      description: "Return toward center.",
      duration: 300,
      composerData: { libraryId: "recover" }
    },
    recenter: {
      id: "recenter",
      label: "Recenter",
      room: "balance",
      type: "transition",
      kind: "journey",
      journeyId: "ground",
      description: "Settle into equilibrium.",
      duration: 300,
      composerData: { libraryId: "ground" }
    }
  },
  connections: [
    ["you", "energize"],
    ["you", "focus"],
    ["you", "explore"],
    ["you", "ground"],
    ["you", "release"],
    ["you", "balance"],
    ["you", "calm"],
    ["you", "drift"],
    ["energize", "focus"],
    ["energize", "balance"],
    ["focus", "ground"],
    ["focus", "explore"],
    ["explore", "release"],
    ["release", "drift"],
    ["ground", "calm"],
    ["ground", "balance"],
    ["calm", "balance"],
    ["calm", "drift"]
  ]
};
